#version: '3.8'
#
#services:
#  app:
#    image: 'docker-spring-boot-postgres:latest'
#    build:
#      context: .
#    container_name: my-app
#    depends_on:
#      - db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=123456
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ht_trac_nghiem
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=123456
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    ports:
#      - "8080:8080"
#
#  db:
#    image: postgres
#    container_name: db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=123456
#      - POSTGRES_DB=ht_trac_nghiem
#    ports:
#      - "5432:5432"
