spring:
  datasource:
    url: postgres://ht_trac_nghiem_user:qijtuPSN2HNvvjLVUFlvYFnV6bS13eqd@dpg-cpen945ds78s73fj7g5g-a.oregon-postgres.render.com/ht_trac_nghiem
    username: ht_trac_nghiem_user
    password: qijtuPSN2HNvvjLVUFlvYFnV6bS13eqd
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
file:
  upload-dir: D:\UploadImageSpring\
cors:
  allowed:
    origins: http://localhost:3000/, http://127.0.0.1:3000/, http://localhost:5432/
  max:
    age: 3600
jwt:
  jwt-key: ~~~!!!!hieuAdmin$$$$%%%%%MultipleChoiceExamSystem%%%%%%$$$$hieuAdmin~~~!!!!
  expiration: 604800000 #7 ngay