spring:
  application:
    name: data
  datasource:
    url: jdbc:postgresql://localhost:5432/ht_trac_nghiem
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
file:
  upload-dir: D:\UploadImageSpring\
cors:
  allowed:
    origins: http://localhost:3000/, http://127.0.0.1:3000/, http://localhost:5432/
  max:
    age: 3600
jwt:
  jwt-key: ~~~!!!!hieuAdmin$$$$%%%%%MultipleChoiceExamSystem%%%%%%$$$$hieuAdmin~~~!!!!
  expiration: 604800000 #7 ngay